version: '2'
services:
 web-cont:
  build:
    context: .
    dockerfile: docker/web.dockerfile.7.1  
    
  # a name for easier reference
  image: projectname-image
  container_name: projectname-web-cont
  volumes:
   - ./html:/var/www/html
  environment:
   - SERVER_NAME=dev.projectname
   - USER_ID=1000
  networks:
   default:
    ipv4_address: 10.0.0.2

#local docker working db
 mysql-cont:
  image: mysql:5.7
  container_name: projectname-mysql-cont
  network_mode: service:web-cont
  environment:
   - MYSQL_ROOT_PASSWORD=dbrootpassword
   - MYSQL_DATABASE=dbname
   - MYSQL_USER=dbuser
   - MYSQL_PASSWORD=dbpassword

# do not use new network use already created one as below
# remember to use the same network name on above
# networks should be same indent of services:
#networks:
#  default:
#    external:
#      name: docker_webapp_network
  
networks:
 app_net:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 10.0.0.0/24
      gateway: 10.0.0.1
